# Generated by Django 4.2 on 2023-04-19 11:17

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_enum_tests_djenum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumtester',
            name='text',
            field=django_enum.fields.EnumCharField(choices=[('V1', 'Value1'), ('V22', 'Value2'), ('V333', 'Value3'), ('D', 'Default')], db_index=True, default=None, max_length=4, null=True),
        ),
    ]
