# Generated by Django 4.2 on 2023-05-04 15:25

import datetime
from decimal import Decimal
from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_enum_tests_djenum', '0002_alter_enumtester_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumtester',
            name='date_enum',
            field=django_enum.fields.EnumDateField(blank=True, choices=[(datetime.date(1984, 8, 7), 'BRIAN'), (datetime.date(1989, 7, 27), 'EMMA'), (datetime.date(2016, 9, 9), 'HUGO')], default=datetime.date(1989, 7, 27)),
        ),
        migrations.AddField(
            model_name='enumtester',
            name='datetime_enum',
            field=django_enum.fields.EnumDateTimeField(blank=True, choices=[(datetime.datetime(1980, 5, 18, 8, 32), 'ST_HELENS'), (datetime.datetime(1991, 6, 15, 20, 9), 'PINATUBO'), (datetime.datetime(2005, 8, 29, 5, 10), 'KATRINA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='enumtester',
            name='decimal_enum',
            field=django_enum.fields.EnumDecimalField(blank=True, choices=[(Decimal('0.99'), 'ONE'), (Decimal('0.999'), 'TWO'), (Decimal('0.9999'), 'THREE'), (Decimal('99.9999'), 'FOUR'), (Decimal('999'), 'FIVE')], decimal_places=4, default=Decimal('0.9999'), max_digits=6),
        ),
        migrations.AddField(
            model_name='enumtester',
            name='duration_enum',
            field=django_enum.fields.EnumDurationField(blank=True, choices=[(datetime.timedelta(days=1), 'DAY'), (datetime.timedelta(days=7), 'WEEK'), (datetime.timedelta(days=14), 'FORTNIGHT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='enumtester',
            name='time_enum',
            field=django_enum.fields.EnumTimeField(blank=True, choices=[(datetime.time(17, 0), 'COB'), (datetime.time(12, 30), 'LUNCH'), (datetime.time(9, 0), 'MORNING')], default=None, null=True),
        ),
    ]
