"""
Migration tests that start from migrations generated by *older releases of
django-enum* and verify that data written by those releases is still read
correctly after migrating to the current release.
See https://github.com/django-commons/django-enum/issues/112

The initial migration of :mod:`tests.legacy_migrations` was generated by
django-enum 2.5.0 (``just make-legacy-migrations``) from the 2.x recipe for
storing the sign bit of a 32/64 bit flag with a negative member value
(https://github.com/django-commons/django-enum/discussions/197). Python 3.15
disallows negative flag values, so django-enum 3.0 spells the top bit
``1 << 31`` and stores it two's complement instead.
See https://github.com/django-commons/django-enum/issues/216
"""

from importlib import import_module

from django.core.management import call_command
from django.db import connection
from django_test_migrations.contrib.unittest_case import MigratorTestCase

APP = "tests_legacy_migrations"
LEGACY = ("tests_legacy_migrations", "0001_initial")
CURRENT = (
    "tests_legacy_migrations",
    "0002_alter_legacyflagmodel_big_permissions_and_more",
)

INT32_MIN = -(2**31)
INT64_MIN = -(2**63)

# (permissions, big_permissions, nullable) exactly as django-enum 2.5.0 wrote
# them - verified by running the v2 models against that release.
LEGACY_ROWS = [
    (INT32_MIN, INT64_MIN, None),  # ADMIN alone, the only thing the recipe could store
    (3, 5, INT32_MIN),  # READ | WRITE, READ | EXECUTE, ADMIN
    (0, 0, None),
    (INT32_MIN + 7, INT64_MIN + 7, 7),  # raw sign bit + low bits, as a hand edit might
]


class TestSignBitUpgradeFrom2x(MigratorTestCase):
    migrate_from = LEGACY
    migrate_to = CURRENT

    def prepare(self):
        model = self.old_state.apps.get_model(APP, "LegacyFlagModel")
        with connection.cursor() as cursor:
            for row in LEGACY_ROWS:
                cursor.execute(
                    f"INSERT INTO {model._meta.db_table} "
                    f"(permissions, big_permissions, nullable) VALUES (%s, %s, %s)",
                    row,
                )

    def test_frozen_migration_is_legacy(self):
        """Guard against the frozen migration being regenerated by 3.x code."""
        source = import_module(f"tests.legacy_migrations.migrations.{LEGACY[1]}")
        self.assertIn("django-enum 2.", open(source.__file__).read())
        create = source.Migration.operations[0]
        fields = dict(create.fields)
        self.assertIn((INT32_MIN, "ADMIN"), fields["permissions"].choices)
        self.assertIn((INT64_MIN, "ADMIN"), fields["big_permissions"].choices)

    def test_migration_is_current(self):
        """The 0002 migration matches the models (no changes pending)."""
        call_command("makemigrations", APP, check=True, dry_run=True, verbosity=0)

    def test_legacy_data_reads_back(self):
        from tests.legacy_migrations.models import (
            LegacyFlagModel,
            Permissions32,
            Permissions64,
        )

        # the column values are untouched by the migration
        with connection.cursor() as cursor:
            cursor.execute(
                f"SELECT permissions, big_permissions, nullable FROM "
                f"{LegacyFlagModel._meta.db_table} ORDER BY id"
            )
            self.assertEqual([tuple(row) for row in cursor.fetchall()], LEGACY_ROWS)

        rows = list(LegacyFlagModel.objects.order_by("pk"))
        self.assertEqual(len(rows), 4)

        self.assertIs(rows[0].permissions, Permissions32.ADMIN)
        self.assertIs(rows[0].big_permissions, Permissions64.ADMIN)
        self.assertIsNone(rows[0].nullable)

        self.assertEqual(rows[1].permissions, Permissions32.READ | Permissions32.WRITE)
        self.assertEqual(
            rows[1].big_permissions, Permissions64.READ | Permissions64.EXECUTE
        )
        self.assertIs(rows[1].nullable, Permissions32.ADMIN)

        self.assertEqual(rows[2].permissions, Permissions32(0))
        self.assertEqual(rows[2].big_permissions, Permissions64(0))

        all32 = (
            Permissions32.ADMIN
            | Permissions32.READ
            | Permissions32.WRITE
            | Permissions32.EXECUTE
        )
        all64 = (
            Permissions64.ADMIN
            | Permissions64.READ
            | Permissions64.WRITE
            | Permissions64.EXECUTE
        )
        self.assertEqual(rows[3].permissions, all32)
        self.assertEqual(rows[3].big_permissions, all64)
        self.assertEqual(
            rows[3].nullable,
            Permissions32.READ | Permissions32.WRITE | Permissions32.EXECUTE,
        )

        for value in [rows[0].permissions, rows[3].permissions]:
            self.assertIsInstance(value, Permissions32)
            self.assertGreater(int(value), 0)

    def test_legacy_data_queries(self):
        from tests.legacy_migrations.models import (
            LegacyFlagModel,
            Permissions32,
            Permissions64,
        )

        rows = list(LegacyFlagModel.objects.order_by("pk"))
        objects = LegacyFlagModel.objects

        self.assertCountEqual(
            objects.filter(permissions__has_any=Permissions32.ADMIN), [rows[0], rows[3]]
        )
        self.assertCountEqual(
            objects.filter(big_permissions__has_any=Permissions64.ADMIN),
            [rows[0], rows[3]],
        )
        self.assertCountEqual(
            objects.filter(
                permissions__has_all=Permissions32.ADMIN | Permissions32.READ
            ),
            [rows[3]],
        )
        self.assertCountEqual(
            objects.filter(
                big_permissions__has_all=Permissions64.ADMIN | Permissions64.READ
            ),
            [rows[3]],
        )
        self.assertCountEqual(
            objects.filter(permissions=Permissions32.ADMIN), [rows[0]]
        )
        self.assertCountEqual(
            objects.filter(big_permissions=Permissions64.ADMIN), [rows[0]]
        )
        self.assertCountEqual(objects.filter(nullable=Permissions32.ADMIN), [rows[1]])
        self.assertCountEqual(objects.filter(nullable__isnull=True), [rows[0], rows[2]])
        self.assertCountEqual(
            objects.exclude(permissions__has_any=Permissions32.ADMIN),
            [rows[1], rows[2]],
        )

        # writes through the new code produce the same representation
        rows[2].permissions = Permissions32.ADMIN
        rows[2].big_permissions = Permissions64.ADMIN | Permissions64.WRITE
        rows[2].save()
        with connection.cursor() as cursor:
            cursor.execute(
                f"SELECT permissions, big_permissions FROM "
                f"{LegacyFlagModel._meta.db_table} WHERE id = %s",
                [rows[2].pk],
            )
            self.assertEqual(tuple(cursor.fetchone()), (INT32_MIN, INT64_MIN + 2))
        self.assertEqual(objects.filter(permissions=Permissions32.ADMIN).count(), 2)
