# Generated by django-enum 2.5.0 (Python 3.14, Django 5.2). FROZEN: do not edit.
# Regenerate with `just make-legacy-migrations`.
# Generated by Django 5.2.17 on 2026-09-06 15:15

import tests.legacy_migrations.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyFlagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    tests.legacy_migrations.fields.SignedIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "READ"),
                            (2, "WRITE"),
                            (4, "EXECUTE"),
                            (-2147483648, "ADMIN"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "big_permissions",
                    tests.legacy_migrations.fields.SignedBigIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "READ"),
                            (2, "WRITE"),
                            (4, "EXECUTE"),
                            (-9223372036854775808, "ADMIN"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "nullable",
                    tests.legacy_migrations.fields.SignedIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "READ"),
                            (2, "WRITE"),
                            (4, "EXECUTE"),
                            (-2147483648, "ADMIN"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
