# Generated by Django 5.2 on 2026-09-06 15:20

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests_legacy_migrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyflagmodel",
            name="big_permissions",
            field=django_enum.fields.BigIntegerFlagField(
                blank=True,
                choices=[
                    (1, "READ"),
                    (2, "WRITE"),
                    (4, "EXECUTE"),
                    (9223372036854775808, "ADMIN"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="legacyflagmodel",
            name="nullable",
            field=django_enum.fields.IntegerFlagField(
                blank=True,
                choices=[
                    (1, "READ"),
                    (2, "WRITE"),
                    (4, "EXECUTE"),
                    (2147483648, "ADMIN"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="legacyflagmodel",
            name="permissions",
            field=django_enum.fields.IntegerFlagField(
                blank=True,
                choices=[
                    (1, "READ"),
                    (2, "WRITE"),
                    (4, "EXECUTE"),
                    (2147483648, "ADMIN"),
                ],
                default=0,
            ),
        ),
    ]
