# Generated by Django 4.2 on 2023-04-19 11:01

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_enum_tests_enum_prop', '0002_alter_enumtester_small_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumtester',
            name='small_int',
            field=django_enum.fields.EnumSmallIntegerField(blank=True, choices=[(-32768, 'Value -32768'), (0, 'Value 0'), (1, 'Value 1'), (2, 'Value 2'), (32767, 'Value 32767')], db_index=True, default=32767),
        ),
    ]
