# Generated by Django 6.0.2 on 2026-02-10 23:37

import django_enum.fields
from django.db import migrations, models
from tests.compat import CheckConstraint


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlagConstraintTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keep",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(4096, "VAL1"), (8192, "VAL2"), (16384, "VAL3")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "eject",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(4096, "VAL1"), (8192, "VAL2"), (16384, "VAL3")],
                        default=0,
                    ),
                ),
                (
                    "eject_non_strict",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(4096, "VAL1"), (8192, "VAL2"), (16384, "VAL3")],
                        default=0,
                    ),
                ),
                (
                    "conform",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(4096, "VAL1"), (8192, "VAL2"), (16384, "VAL3")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "strict",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(4096, "VAL1"), (8192, "VAL2"), (16384, "VAL3")],
                        default=None,
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    CheckConstraint(
                        condition=models.Q(
                            models.Q(("eject__gte", 4096), ("eject__lte", 28672)),
                            ("eject", 0),
                            _connector="OR",
                        ),
                        name="sts_flag_constraints_FlagConstraintTestModel_eject_EjectFlagEnum",
                    ),
                    CheckConstraint(
                        condition=models.Q(
                            models.Q(("conform__gte", 4096), ("conform__lte", 28672)),
                            ("conform", 0),
                            ("conform__isnull", True),
                            _connector="OR",
                        ),
                        name="flag_constraints_FlagConstraintTestModel_conform_ConformFlagEnum",
                    ),
                    CheckConstraint(
                        condition=models.Q(
                            models.Q(("strict__gte", 4096), ("strict__lte", 28672)),
                            ("strict", 0),
                            ("strict__isnull", True),
                            _connector="OR",
                        ),
                        name="s_flag_constraints_FlagConstraintTestModel_strict_StrictFlagEnum",
                    ),
                ],
            },
        ),
    ]
