# Generated by Django 4.2 on 2026-02-10 23:32

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlagConstraintTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_field",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(4096, "VAL1"), (8192, "VAL2"), (16384, "VAL3")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "flag_field_non_strict",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(4096, "VAL1"), (8192, "VAL2"), (16384, "VAL3")],
                        default=None,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
