# Generated by Django 4.2 on 2026-02-11 11:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields
import pathlib
import tests.examples.models.custom_value
from tests.compat import CheckConstraint


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_enum', django_enum.fields.EnumCharField(blank=True, choices=[('V0', 'Value 0'), ('V1', 'Value 1'), ('V2', 'Value 2')], default=None, max_length=2, null=True)),
                ('int_enum', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesWithProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django_enum.fields.EnumCharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomValueExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_props', django_enum.fields.EnumCharField(choices=[(tests.examples.models.custom_value.StrProps('str1'), 'STR1'), (tests.examples.models.custom_value.StrProps('str2'), 'STR2'), (tests.examples.models.custom_value.StrProps('str3'), 'STR3')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='EquivalencyExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_enum', django_enum.fields.EnumCharField(blank=True, choices=[('V0', 'Value 0'), ('V1', 'Value 1'), ('V2', 'Value 2')], default=None, max_length=2, null=True)),
                ('txt_choices', models.CharField(blank=True, choices=[('V0', 'Value 0'), ('V1', 'Value 1'), ('V2', 'Value 2')], default=None, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_enum1', django_enum.fields.EnumCharField(choices=[('V0', 'VALUE0'), ('V1', 'VALUE1'), ('V2', 'VALUE2')], max_length=2)),
                ('txt_enum2', django_enum.fields.EnumCharField(choices=[('V0', 'VALUE0'), ('V1', 'VALUE1'), ('V2', 'VALUE2')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FlagExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', django_enum.fields.SmallIntegerFlagField(blank=True, choices=[(1, 'READ'), (2, 'WRITE'), (4, 'EXECUTE')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GNSSReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constellations', django_enum.fields.SmallIntegerFlagField(blank=True, choices=[(1, 'GPS'), (2, 'GLONASS'), (4, 'GALILEO'), (8, 'BEIDOU'), (16, 'QZSS'), (32, 'IRNSS')], db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GNSSReceiverBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps', models.BooleanField(default=False)),
                ('glonass', models.BooleanField(default=False)),
                ('galileo', models.BooleanField(default=False)),
                ('beidou', models.BooleanField(default=False)),
                ('qzss', models.BooleanField(default=False)),
                ('irnss', models.BooleanField(default=False)),
                ('sbas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', django_enum.fields.SmallIntegerFlagField(blank=True, choices=[(1, 'READ'), (2, 'WRITE'), (4, 'EXECUTE'), (7, 'RWX')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HashEquivalencyExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_hash_eq', django_enum.fields.EnumCharField(choices=[('V1', 'VALUE1'), ('V2', 'VALUE2'), ('V3', 'VALUE3')], max_length=2)),
                ('hash_eq', django_enum.fields.EnumCharField(choices=[('V1', 'VALUE1'), ('V2', 'VALUE2'), ('V3', 'VALUE3')], max_length=2)),
                ('hash_eq_str', django_enum.fields.EnumCharField(choices=[('V1', 'VALUE1'), ('V2', 'VALUE2'), ('V3', 'VALUE3')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'Streets'), (2, 'Outdoors'), (3, 'Light'), (4, 'Dark'), (5, 'Satellite'), (6, 'Satellite Streets'), (7, 'Navigation Day'), (8, 'Navigation Night')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MixedValueExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eccentric_str', django_enum.fields.EnumCharField(choices=[(None, 'NONE'), (1, 'VAL1'), ('2.0', 'VAL2'), (3.0, 'VAL3'), (Decimal('4.5'), 'VAL4')], max_length=3, null=True)),
                ('eccentric_float', django_enum.fields.EnumFloatField(choices=[(None, 'NONE'), (1, 'VAL1'), ('2.0', 'VAL2'), (3.0, 'VAL3'), (Decimal('4.5'), 'VAL4')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoCoerceExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_strict', django_enum.fields.EnumCharField(choices=[('1', 'One'), ('2', 'Two')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PathValueExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_enum.fields.EnumCharField(choices=[(pathlib.PurePosixPath('/usr'), 'USR'), (pathlib.PurePosixPath('/usr/local'), 'USR_LOCAL'), (pathlib.PurePosixPath('/usr/local/bin'), 'USR_LOCAL_BIN')], max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django_enum.fields.EnumCharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StrictExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_strict', django_enum.fields.EnumCharField(choices=[('1', 'One'), ('2', 'Two')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TextChoicesExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django_enum.fields.EnumCharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetDemoNonStrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django_enum.fields.EnumCharField(choices=[('R', 'RED'), ('G', 'GREEN'), ('B', 'BLUE')], max_length=12)),
                ('permissions', django_enum.fields.SmallIntegerFlagField(blank=True, choices=[(1, 'READ'), (2, 'WRITE'), (4, 'EXECUTE')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetDemoRadiosAndChecksNulls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django_enum.fields.EnumCharField(blank=True, choices=[('R', 'RED'), ('G', 'GREEN'), ('B', 'BLUE')], default=None, max_length=1, null=True)),
                ('permissions', django_enum.fields.SmallIntegerFlagField(blank=True, choices=[(1, 'READ'), (2, 'WRITE'), (4, 'EXECUTE')], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetDemoStrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django_enum.fields.EnumCharField(choices=[('R', 'RED'), ('G', 'GREEN'), ('B', 'BLUE')], default='R', max_length=1)),
                ('permissions', django_enum.fields.SmallIntegerFlagField(blank=True, choices=[(1, 'READ'), (2, 'WRITE'), (4, 'EXECUTE')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetDemoRadiosAndChecks',
            fields=[
                ('widgetdemostrict_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests_examples.widgetdemostrict')),
            ],
            bases=('tests_examples.widgetdemostrict',),
        ),
        migrations.CreateModel(
            name='WidgetDemoRadiosAndChecksNonStrict',
            fields=[
                ('widgetdemononstrict_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests_examples.widgetdemononstrict')),
            ],
            bases=('tests_examples.widgetdemononstrict',),
        ),
        migrations.AddConstraint(
            model_name='widgetdemostrict',
            constraint=CheckConstraint(condition=models.Q(('color__in', ['R', 'G', 'B'])), name='tests_examples_WidgetDemoStrict_color_Color'),
        ),
        migrations.AddConstraint(
            model_name='widgetdemoradiosandchecksnulls',
            constraint=CheckConstraint(condition=models.Q(('color__in', ['R', 'G', 'B']), ('color__isnull', True), _connector='OR'), name='tests_examples_WidgetDemoRadiosAndChecksNulls_color_Color'),
        ),
        migrations.AddConstraint(
            model_name='textchoicesexample',
            constraint=CheckConstraint(condition=models.Q(('color__in', ['R', 'G', 'B'])), name='tests_examples_TextChoicesExample_color_Color'),
        ),
        migrations.AddConstraint(
            model_name='propertyexample',
            constraint=CheckConstraint(condition=models.Q(('color__in', ['R', 'G', 'B'])), name='tests_examples_PropertyExample_color_Color'),
        ),
        migrations.AddConstraint(
            model_name='pathvalueexample',
            constraint=CheckConstraint(condition=models.Q(('path__in', ['/usr', '/usr/local', '/usr/local/bin'])), name='tests_examples_PathValueExample_path_PathEnum'),
        ),
        migrations.AddConstraint(
            model_name='mixedvalueexample',
            constraint=CheckConstraint(condition=models.Q(('eccentric_str__in', [None, '1', '2.0', '3.0', '4.5']), ('eccentric_str__isnull', True), _connector='OR'), name='tests_examples_MixedValueExample_eccentric_str_MixedValueEnum'),
        ),
        migrations.AddConstraint(
            model_name='mixedvalueexample',
            constraint=CheckConstraint(condition=models.Q(('eccentric_float__in', [None, 1.0, 2.0, 3.0, 4.5]), ('eccentric_float__isnull', True), _connector='OR'), name='tests_examples_MixedValueExample_eccentric_float_MixedValueEnum'),
        ),
        migrations.AddConstraint(
            model_name='map',
            constraint=CheckConstraint(condition=models.Q(('style__in', [1, 2, 3, 4, 5, 6, 7, 8])), name='tests_examples_Map_style_MapBoxStyle'),
        ),
        migrations.AddConstraint(
            model_name='hashequivalencyexample',
            constraint=CheckConstraint(condition=models.Q(('not_hash_eq__in', ['V1', 'V2', 'V3'])), name='tests_examples_HashEquivalencyExample_not_hash_eq_NotHashEq'),
        ),
        migrations.AddConstraint(
            model_name='hashequivalencyexample',
            constraint=CheckConstraint(condition=models.Q(('hash_eq__in', ['V1', 'V2', 'V3'])), name='tests_examples_HashEquivalencyExample_hash_eq_HashEq'),
        ),
        migrations.AddConstraint(
            model_name='hashequivalencyexample',
            constraint=CheckConstraint(condition=models.Q(('hash_eq_str__in', ['V1', 'V2', 'V3'])), name='tests_examples_HashEquivalencyExample_hash_eq_str_HashEqStr'),
        ),
        migrations.AddIndex(
            model_name='gnssreceiverbasic',
            index=models.Index(fields=['gps', 'glonass', 'galileo', 'beidou', 'qzss', 'irnss', 'sbas'], name='tests_examp_gps_97c3db_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalchoices',
            constraint=CheckConstraint(condition=models.Q(('txt_enum1__in', ['V0', 'V1', 'V2'])), name='tests_examples_ExternalChoices_txt_enum1_TextEnum'),
        ),
        migrations.AddConstraint(
            model_name='externalchoices',
            constraint=CheckConstraint(condition=models.Q(('txt_enum2__in', ['V0', 'V1', 'V2'])), name='tests_examples_ExternalChoices_txt_enum2_TextEnum'),
        ),
        migrations.AddConstraint(
            model_name='equivalencyexample',
            constraint=CheckConstraint(condition=models.Q(('txt_enum__in', ['V0', 'V1', 'V2']), ('txt_enum__isnull', True), _connector='OR'), name='tests_examples_EquivalencyExample_txt_enum_TextEnum'),
        ),
        migrations.AddConstraint(
            model_name='customvalueexample',
            constraint=CheckConstraint(condition=models.Q(('str_props__in', ['str1', 'str2', 'str3'])), name='tests_examples_CustomValueExample_str_props_StrPropsEnum'),
        ),
        migrations.AddConstraint(
            model_name='choiceswithproperties',
            constraint=CheckConstraint(condition=models.Q(('color__in', ['R', 'G', 'B'])), name='tests_examples_ChoicesWithProperties_color_Color'),
        ),
        migrations.AddConstraint(
            model_name='basicexample',
            constraint=CheckConstraint(condition=models.Q(('txt_enum__in', ['V0', 'V1', 'V2']), ('txt_enum__isnull', True), _connector='OR'), name='tests_examples_BasicExample_txt_enum_TextEnum'),
        ),
        migrations.AddConstraint(
            model_name='basicexample',
            constraint=CheckConstraint(condition=models.Q(('int_enum__in', [1, 2, 3])), name='tests_examples_BasicExample_int_enum_IntEnum'),
        ),
    ]
