"""
The django-enum 2.x work-around for storing the sign bit of a 32 or 64 bit
flag, as recommended in
https://github.com/django-commons/django-enum/discussions/197.

A user that followed that recipe keeps this module around so that the
migrations generated while it was in use remain importable. It is
referenced by ``migrations/0001_initial.py`` which was generated by
django-enum 2.5.0 and must never be edited.
"""

from typing import Generic

from django_enum.fields import (
    EnumBigIntegerField,
    EnumIntegerField,
    FlagField,
    FlagT,
)


class SignedIntegerFlagField(
    FlagField[int, FlagT], EnumIntegerField[FlagT], Generic[FlagT]
):
    pass


class SignedBigIntegerFlagField(
    FlagField[int, FlagT], EnumBigIntegerField[FlagT], Generic[FlagT]
):
    pass
