name: release

on:
  release:
    types: [published]


jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  pypi:
    runs-on: ubuntu-latest
    needs: test
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build package
        run: |
          uv build

      - name: Upload release assets to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./dist/*

      - name: Publish to PyPI
        run: |
          uv publish
